### Get Request
GET http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/get-tickers/nifty500
Content-Type: application/json

### Post Request
POST http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/tradesignals/nifty500
Content-Type: application/json

### Post Request
POST http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/tradesignal-single/SUNDARMFIN.NS
Content-Type: application/json

### Get Request
GET http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/tradesignals/getresult/2dc03d98-b2fe-49ea-9ae3-7784b8f7e18d
Content-Type: application/json

### Post Request
POST http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/backtrade/SUNDARMFIN.NS
Content-Type: application/json

### Get Request - FirebaseFunctions
GET https://amazing-stocks-be-cvgblhnzpa-uc.a.run.app/tradesignals/nifty50
Content-Type: application/json


### Get Request
GET https://amazing-stocks-be-cvgblhnzpa-uc.a.run.app/tradesignals/getresult/b2e42627-1bd6-4089-b785-8e49ff1ac522
Content-Type: application/json


### Get Request
GET https://amazing-stocks-be-cvgblhnzpa-uc.a.run.app/backtrade/HDFCBANK.NS
Content-Type: application/json
