### Get Request
GET http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/tradesignals/nifty500
Content-Type: application/json

### Get Request
GET http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/tradesignals/getresult/aefc4033-0b13-47c1-adc9-81412f2c525a
Content-Type: application/json

### Get Request
GET http://127.0.0.1:5001/amazingstocks-9829a/us-central1/amazing_stocks_be/backtrade/HDFCBANK.NS
Content-Type: application/json

### Get Request - FirebaseFunctions
GET https://amazing-stocks-be-cvgblhnzpa-uc.a.run.app/tradesignals/nifty50
Content-Type: application/json


### Get Request
GET https://amazing-stocks-be-cvgblhnzpa-uc.a.run.app/tradesignals/getresult/b2e42627-1bd6-4089-b785-8e49ff1ac522
Content-Type: application/json


### Get Request
GET https://amazing-stocks-be-cvgblhnzpa-uc.a.run.app/backtrade/HDFCBANK.NS
Content-Type: application/json
